from django.contrib import admin

from . import models

admin.site.register(models.Status)
admin.site.register(models.CustomerType)
admin.site.register(models.OvertimeType)
admin.site.register(models.DriveTimeCode)
admin.site.register(models.ValuationType)
admin.site.register(models.PaymentType)
admin.site.register(models.Competitor)
admin.site.register(models.OvertimeCode)
admin.site.register(models.Location)
admin.site.register(models.EffectiveRate)
admin.site.register(models.RateSchedule)
admin.site.register(models.Customer)
admin.site.register(models.ContactTitle)
admin.site.register(models.Contact)
admin.site.register(models.EstimateType)
admin.site.register(models.ProposalType)
admin.site.register(models.PricingType)
admin.site.register(models.AdditionalChargeType)
admin.site.register(models.PrevailingWage)
admin.site.register(models.Contractor)
admin.site.register(models.Estimate)
admin.site.register(models.WorkOrderGroup)
admin.site.register(models.CustomerAddress)
admin.site.register(models.ServiceLine)
admin.site.register(models.WorkOrder)
admin.site.register(models.WorkOrderComment)
admin.site.register(models.EquipmentItem)
admin.site.register(models.InstallationService)
admin.site.register(models.LaborCategory)
admin.site.register(models.LaborTask)
admin.site.register(models.Material)
admin.site.register(models.VehicleType)
admin.site.register(models.Unit)
admin.site.register(models.WorkOrderEquipmentItem)
admin.site.register(models.WorkOrderInstallService)
admin.site.register(models.WorkOrderLaborTask)
admin.site.register(models.WorkOrderMaterial)
admin.site.register(models.WorkOrderUnit)
admin.site.register(models.WorkOrderVehicle)

# Register your models here.
